config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :project, only: [:index]
  resources :contact, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def projects

  end

  def contact

  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contact/index.html.erb
<div class="page d-flex align-items-center justify-content-center">
  <div class="banner">
    <h3>dev.jwagner@gmail.com</h3>
    <h3>+33 7 67 73 90 66</h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Jonathan Wagner</title>
    <meta name="description" content="Site portfolio de Jonathan Wagner - Full Stack Developer !">

    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="twitter:card" content="summary_large_image">
   <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
   <meta name="twitter:title" content="<%= meta_title %>">
   <meta name="twitter:description" content="<%= meta_description %>">
   <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
   <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="page d-flex align-items-center justify-content-center">
  <div class="banner" id="scrolldown">
    <h1>Jonathan Wagner</h1>
    <h3>Full Stack Web Developer</h3>

    <a href="#two" class="btn btn-dark">About</a>

  </div>
</div>


<div class="about">
  <div class="about-text">
    <h2 id="two"></h2>
    <h2 id="about">About me</h2>
    <p class="text-justify">To start with, I would say that I have a very atypical professional career! <br>
     I first started as an opera singer, training at the Conservatory of Music of Bordeaux and later singing in worldwide stages. After 3 years, I moved to Paris and learned Musical Theater at the International Academy of Musical Theater where I was taugh how to sing, act and dance! Concomitantly to this, I finished my opera training at the Conservatory of Maisons-Alfort. 1 year after both graduations, I decided to move to the Philippines to improve my artistic skills and discover new professional horizons. <br>
    Luckily, it wasn't long until I had the chance to meet the right persons (Chief consultant, Head of Business Intelligence and Analytics at Sencor and former President and CEO of Bankard) who mentored me to become a <strong>consultant in Business Development</strong>, specializing in <strong>Operation Control</strong> (real estate industry) and in <strong>Data analytics</strong> (Stock Market industry), challenging myself everyday and sharpening my logic and my business side. <br>
    Curious by nature and willing to improve my communication skills, I decided to take an exam which led me to become a part-time <strong>French Teacher</strong> in a Filipino business school (Enderun College). <br>
    As I quickly developed a bigger interest for business and triggered by the high economic growth of the country, I opened my own 4 employees business, selling sweets in one of the largest mall of the Philippines. <br>
    After 4 years living abroad, full of experiences and ideas, I came back to Bordeaux and started to learn how to <strong>code in C</strong>, excited to know more about the growing tech industry. Quickly realizing that coding was combining my artistic side (front), logical side (back) and my business side, I decided to join <strong>Le Wagon School</strong> Bordeaux where I learned how to properly code in <strong>Ruby, Rails, HTML5, CSS3, JavaScript</strong> and use other technologies (SQL, MySQL, PostgreSQL, Git, GitHub, Heroku, Stripe, MapBox, Action Cable, Algolia, Devise, Pundit, Figma...). Right after obtaining my <strong>Level 2 RNCP Web Developer Certificate</strong> in September 2019, I became a Teacher Assistant at the Wagon Bordeaux School and started 2 professional projects for Europe and Asia. At the same time, I learned <strong>data analytics</strong> using <strong>Python, NumPy, Pandas, SciPy, Matplotlib, Seaborn, Hadoop and Qlikview</strong>. </p>
  </div>
</div>

app/views/project/index.html.erb
<div class="container">

  <a href="https://qultur.herokuapp.com/" target=”_blank”>
    <div class="cover atvImg">
      <div class="atvImg-layer" data-img="https://res.cloudinary.com/my-apps-le-wagon/image/upload/v1570364170/Screenshot_from_2019-10-06_13-55-12_1_exzmz5.png"></div>
    </div>
  </a>

  <a href="https://rent-my-cat.herokuapp.com/" target=”_blank”>
    <div class="cover atvImg">
      <div class="atvImg-layer" data-img="https://res.cloudinary.com/my-apps-le-wagon/image/upload/v1570461730/Screenshot_from_2019-10-07_17-20-34_sjorij.png"></div>
    </div>
  </a>

  <a href="#" target=”_blank”>
    <div class="cover atvImg">
      <div class="atvImg-layer" data-img="https://res.cloudinary.com/my-apps-le-wagon/image/upload/v1572452643/Ongoingproject_etv82m.jpg"></div>
    </div>
  </a>

  <a href="#" target=”_blank”>
    <div class="cover atvImg">
      <div class="atvImg-layer" data-img="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg"></div>
    </div>
  </a>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-wrapper">
    <a class="footer-icon facebook" href="https://www.facebook.com/jonathan.wagner.90" target="_blank">
       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="30px"
          viewBox="0 0 512 512" fill="#385C8E" style="enable-background:new 0 0 512 512;" xml:space="preserve">
          <g>
             <path d="M134.941,272.691h56.123v231.051c0,4.562,3.696,8.258,8.258,8.258h95.159c4.562,0,8.258-3.696,8.258-8.258V273.78h64.519c4.195,0,7.725-3.148,8.204-7.315l9.799-85.061c0.269-2.34-0.472-4.684-2.038-6.44c-1.567-1.757-3.81-2.763-6.164-2.763h-74.316V118.88c0-16.073,8.654-24.224,25.726-24.224c2.433,0,48.59,0,48.59,0c4.562,0,8.258-3.698,8.258-8.258V8.319c0-4.562-3.696-8.258-8.258-8.258h-66.965C309.622,0.038,308.573,0,307.027,0c-11.619,0-52.006,2.281-83.909,31.63c-35.348,32.524-30.434,71.465-29.26,78.217v62.352h-58.918c-4.562,0-8.258,3.696-8.258,8.258v83.975C126.683,268.993,130.379,272.691,134.941,272.691z"/>
          </g>
       </svg>
    </a>
    <a class="footer-icon linkedin" href="https://www.linkedin.com/in/jonathan-wagner-33000" target="_blank">
       <svg style="enable-background:new 0 0 64 64;" version="1.1" viewBox="0 0 64 64" xml:space="preserve" width="35px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#0072FF">
          <g>
             <path d="M8,54.7C8,55.4,8.6,56,9.3,56h9.3c0.7,0,1.3-0.6,1.3-1.3V23.9c0-0.7-0.6-1.3-1.3-1.3H9.3   c-0.7,0-1.3,0.6-1.3,1.3V54.7z"/>
             <path d="M46.6,22.3c-4.5,0-7.7,1.8-9.4,3.7c-0.4,0.4-1.1,0.1-1.1-0.5l0-1.6c0-0.7-0.6-1.3-1.3-1.3h-9.4   c-0.7,0-1.3,0.6-1.3,1.3c0.1,5.7,0,25.4,0,30.7c0,0.7,0.6,1.3,1.3,1.3h9.5c0.7,0,1.3-0.6,1.3-1.3V37.9c0-1,0-2,0.3-2.7c0.8-2,2.6-4.1,5.7-4.1c4.1,0,6,3.1,6,7.6v15.9c0,0.7,0.6,1.3,1.3,1.3h9.3c0.7,0,1.3-0.6,1.3-1.3V37.4C60,27.1,54.1,22.3,46.6,22.3z"/>
             <path d="M13.9,18.9L13.9,18.9c3.8,0,6.1-2.4,6.1-5.4C19.9,10.3,17.7,8,14,8c-3.7,0-6,2.3-6,5.4   C8,16.5,10.3,18.9,13.9,18.9z"/>
          </g>
       </svg>
    </a>
    <a class="footer-icon instagram" href="https://www.instagram.com/iamjonathanwagner/" target="_blank">
       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="35px"
          viewBox="0 0 551.034 551.034" xml:space="preserve">
          <g>
             <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="275.517" y1="4.57" x2="275.517" y2="549.72" gradientTransform="matrix(1 0 0 -1 0 554)">
             <stop  offset="0" style="stop-color:#E09B3D"/>
             <stop  offset="0.3" style="stop-color:#C74C4D"/>
             <stop  offset="0.6" style="stop-color:#C21975"/>
             <stop  offset="1" style="stop-color:#7024C4"/>
          </linearGradient>
          <path class="insta-square" style="fill:url(#SVGID_1_);" d="M386.878,0H164.156C73.64,0,0,73.64,0,164.156v222.722
             c0,90.516,73.64,164.156,164.156,164.156h222.722c90.516,0,164.156-73.64,164.156-164.156V164.156
             C551.033,73.64,477.393,0,386.878,0z M495.6,386.878c0,60.045-48.677,108.722-108.722,108.722H164.156
             c-60.045,0-108.722-48.677-108.722-108.722V164.156c0-60.046,48.677-108.722,108.722-108.722h222.722
             c60.045,0,108.722,48.676,108.722,108.722L495.6,386.878L495.6,386.878z"/>

             <linearGradient id="SVGID_2_" gradientUnits="userSpaceOnUse" x1="275.517" y1="4.57" x2="275.517" y2="549.72" gradientTransform="matrix(1 0 0 -1 0 554)">
             <stop  offset="0" style="stop-color:#E09B3D"/>
             <stop  offset="0.3" style="stop-color:#C74C4D"/>
             <stop  offset="0.6" style="stop-color:#C21975"/>
             <stop  offset="1" style="stop-color:#7024C4"/>
          </linearGradient>
          <path style="fill:url(#SVGID_2_);" d="M275.517,133C196.933,133,133,196.933,133,275.516s63.933,142.517,142.517,142.517
             S418.034,354.1,418.034,275.516S354.101,133,275.517,133z M275.517,362.6c-48.095,0-87.083-38.988-87.083-87.083
             s38.989-87.083,87.083-87.083c48.095,0,87.083,38.988,87.083,87.083C362.6,323.611,323.611,362.6,275.517,362.6z"/>

          <linearGradient id="SVGID_3_" gradientUnits="userSpaceOnUse" x1="418.31" y1="4.57" x2="418.31" y2="549.72" gradientTransform="matrix(1 0 0 -1 0 554)">
             <stop  offset="0" style="stop-color:#E09B3D"/>
             <stop  offset="0.3" style="stop-color:#C74C4D"/>
             <stop  offset="0.6" style="stop-color:#C21975"/>
             <stop  offset="1" style="stop-color:#7024C4"/>
          </linearGradient>
             <circle style="fill:url(#SVGID_3_);" cx="418.31" cy="134.07" r="34.15"/>
          </g>
       </svg>
    </a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                  <%= link_to "Home", root_path, class: "nav-link link-nodeco"%>
              </li>
              <li class="nav-item">
                  <%= link_to "Projects", project_index_path, class: "nav-link link-nodeco"%>
              </li>
              <li class="nav-item">
                  <%= link_to "Contact", contact_index_path, class: "nav-link link-nodeco"%>
              </li>
          </ul>
      </div>
  </nav>